### PR TITLE
Creating sparkSession and submitting spark job with PySpark

### PR DESCRIPTION
**Pull request by Polischuk1**

### CODE REVIEW

**Comment by Polischuk1** [comment]
When I create a new branch, files from the previous branch are automatically included, and I need to delete them. Additionally, I’ve noticed that the _sql folder is missing from the main branch, and I’m unsure how this occurred.

This situation has led to some merge conflicts that I can’t seem to resolve. When I run git status, it doesn’t show any conflicts in the main or other branches.
Could you help me out with this problem? Thank you

**Comment by maksymloktionov** [comment]
Something strange is happening with your branches. Please check on why other files are deleted

**Comment by maksymloktionov** [comment]
Please fix the PR

**Comment by maksymloktionov** [comment]
It is still not fixed, there are a lot of deleted files

**Comment by maksymloktionov** [comment]
I think there is something strange there happening as well. Before marking this PR as ready for review, please take a look at it on your side. There are 342 files to review, but in reality I want to review only the batch processing(spark) piece, other things should stay the same

**Pull request closed without merging**
